name: tracker-scripts
channels:
  - esri
  - defaults
dependencies:
  - arcgis>=1.6.2
  - pendulum=1.4.4
  - pip>=19.1.1
  - python=3.6.8
  - seaborn=0.9.0
  - shapely=1.6.4
  - pip:
      - pyqrcode==1.2.1
      - pypng==0.0.18
